added tasks

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,27 +1,26 @@
 #!/usr/bin/env bash
-#cheking for command line arguments
-
+# Checking for command-line argument
 if [ $# -lt 4 ]
 then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-	exit 1
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
-#assign pramters to variables
+# Assigning Arguments to variables
 
-PATH_TO_FILE=$1
+path_to_file=$1
 ip=$2
 username=$3
-PATH_TO_SSH_KEY=$4
+path_to_ssh_key=$4
 
-# disable
 
-scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$PATH_TO_FILE" "$username@ip:~/"
+# Disabbling Strict Host Key checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
 
-#cheking if the fiel transfer was success process
+# Checking if the transfer was successful
 if [ $? -eq 0 ]
 then
-	echo "file transfer success"
+  echo "FILE TRANSFER WAS SUCCESSFULL"
 else
-	echo "file failed to transfer"
+  echo "FILE TRANSFER FAILED"
 fi
